FR-718: Withdrawals list
rbkmoney/dashboard pull request #551
Opened 2021-08-18 15:19 UTC by DenisHedgehog

## ⛵ JIRA

-   [ ] [FR-718](https://rbkmoney.atlassian.net/browse/FR-718)

## 📑 Изменения

```
Список возвратов
```

### 📦 Новые NPM пакеты

-   [ ] Добавлены новые NPM пакеты

### 📚 Обновлен Guideline

-   [ ] Добавлено описание в [wiki](https://github.com/rbkmoney/dashboard/wiki)

## 🖥️ Изменения в интерфейсе

-   [ ] Да
-   [ ] Выглядит отлично на мобильных устройствах

### 🔗 Страницы с изменениями либо как их воспроизвести

-  http://localhost:8000/wallet-section/withdrawals

### 🖼 Скриншоты

2021-08-19 08:55 UTC, KrickRay requested changes

2021-08-19 08:55 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-expanded-id-manager.service.ts
> +import { Injectable } from '@angular/core';
Сервисы должны лежать в services

2021-08-19 15:09 UTC, KrickRay approved these changes

2021-08-20 10:31 UTC, KeinAsylum approved these changes

2021-08-20 12:00 UTC, merged