FR-721: Withdrawals other filters
rbkmoney/dashboard pull request #560
Opened 2021-08-30 17:21 UTC by DenisHedgehog

## ⛵ JIRA

-   [ ] [FR-721](https://rbkmoney.atlassian.net/browse/FR-721)

## 📑 Изменения

```
Добавлены "Другие фильтры" в раздел "Выводы"
```

### 📦 Новые NPM пакеты

-   [ ] Добавлены новые NPM пакеты

### 📚 Обновлен Guideline

-   [ ] Добавлено описание в [wiki](https://github.com/rbkmoney/dashboard/wiki)

## 🖥️ Изменения в интерфейсе

-   [ ] Да
-   [ ] Выглядит отлично на мобильных устройствах

### 🔗 Страницы с изменениями либо как их воспроизвести

-   http://localhost:8000/wallet-section/withdrawals

### 🖼 Скриншоты

![image](https://user-images.githubusercontent.com/17727894/131378817-4084f534-abd4-4126-86dc-898ec0c22512.png)

2021-08-31 09:35 UTC, KrickRay requested changes

2021-08-31 09:35 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.ts
> +    });
я думаю в современных реалиях с s-libs стоит использовать его для создания доп фильтров
`WrappedFormControlSuperclass`

2021-08-31 09:40 UTC, KrickRay requested changes

2021-08-31 09:40 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.html
> +        <div class="kek" fxLayout="column" fxLayoutGap="8px">
🤡

2021-08-31 09:40 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.scss
> +}
поч так приходится делать?

2021-08-31 09:40 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.ts
> +    }
эти геттеры должны самоуничтожиться вместе с s-libs

2021-08-31 09:41 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.ts
> +    }
я бы и от этого избавился/переделал, можно обсудить как именно после того как заиспользуешь s-libs

2021-08-31 11:29 UTC, DenisHedgehog commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.scss
> +}
Потому что в base-dialog зашит отступ от контента 24 пикселя, а по макету нужен отступ 8 пикселей. Возможно стоит отдельно избавиться от отступа в самом диалоге

2021-08-31 11:49 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.scss
> +}
не должно такой проблемы возникать, @KeinAsylum может прояснит

2021-08-31 11:51 UTC, KeinAsylum commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.scss
> +}
В каком месте? Таких переопределений не должно быть. Нужно будет поменять макет.

2021-08-31 12:04 UTC, DenisHedgehog commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.scss
> +}
Вот в base-dialog зашит gap между контентом и экшенами

![image](https://user-images.githubusercontent.com/17727894/131499207-3b7c37f2-862e-4303-9897-d31bc02f5e08.png)

2021-08-31 12:11 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/components/dialog-filters/dialog-filters.component.scss
> +}
а почему в шаблоне 8?

2021-08-31 13:26 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/withdrawal-sum-filter/types/withdrawal-sum-filter.ts
> +    max: string | number;
здесь наверное однозначно должно быть (number)

2021-09-03 11:12 UTC, KrickRay commented
<img width="551" alt="Screenshot 2021-09-03 at 14 11 15" src="https://user-images.githubusercontent.com/11846445/131996442-146480f0-3a94-4a08-8f3e-66a719888fed.png">
интересно что если ввести например мин и сбросить то перестает показывать подпись

2021-09-03 11:23 UTC, KrickRay requested changes

2021-09-03 11:23 UTC, KrickRay commented on src/app/sections/wallet-section/deposits/deposits-filters/deposits-filters.component.ts
> +                filter((v) => !isEqual(v, data))
take 1 бесполезный
а untilDestroyed был наоборот нужен

2021-09-03 11:23 UTC, KrickRay commented on src/app/sections/wallet-section/withdrawals/withdrawals-filters/additional-filters/utils/filters-to-form.ts
> +    });
должно работать и без prepareFormObject (removeDictEmptyFields должен и так пустой объект удалить)

(PS название для функции плохое, что то по аналогии можно было бы removeDictEmptyFieldsWithObjects)

2021-09-03 14:08 UTC, KrickRay approved these changes

2021-09-03 14:13 UTC, merged