FR-749: Bootstrap icons
rbkmoney/dashboard pull request #588
Opened 2021-11-16 15:18 UTC by DenisHedgehog

## ⛵ JIRA

-   [ ] [FR-749](https://rbkmoney.atlassian.net/browse/FR-749)

## 📑 Изменения

```
Заменены иконки на bootstrap icons. Удален компонен colored icon.
```

### 📦 Новые NPM пакеты

-   [ ] Добавлены новые NPM пакеты

### 📚 Обновлен Guideline

-   [ ] Добавлено описание в [wiki](https://github.com/rbkmoney/dashboard/wiki)

## 🖥️ Изменения в интерфейсе

-   [ ] Да
-   [ ] Выглядит отлично на мобильных устройствах

### 🔗 Страницы с изменениями либо как их воспроизвести

-   http://localhost:8000/payment-section
-   http://localhost:8000/wallet-section
-   http://localhost:8000/claim-section/claims/{claimID}
-   http://localhost:8000/payment-section/realm/live/operations/payments

### 🖼 Скриншоты
ДО:
![image](https://user-images.githubusercontent.com/17727894/142012066-08e3e5a5-d246-4df3-aa34-3a2975d9206b.png)
ПОСЛЕ:
![image](https://user-images.githubusercontent.com/17727894/142012361-bafd0896-f795-4845-9865-a9a9e2d96406.png)

ДО:
![image](https://user-images.githubusercontent.com/17727894/142012451-1e771bbd-df9f-496c-9b65-69c8f08b38cf.png)
ПОСЛЕ:
![image](https://user-images.githubusercontent.com/17727894/142012494-f00b16b8-8934-415a-a64d-73092e656704.png)

ДО:
![image](https://user-images.githubusercontent.com/17727894/142012580-91267dc4-35c6-4360-9233-021a22a5b5f8.png)
ПОСЛЕ:
![image](https://user-images.githubusercontent.com/17727894/142012636-33b87209-77c5-445d-a168-733ab4fc72a0.png)

ДО:
![image](https://user-images.githubusercontent.com/17727894/142012738-469cd9a6-d6e2-4f92-9a72-73285f51842b.png)
ПОСЛЕ:
![image](https://user-images.githubusercontent.com/17727894/142012806-96d115f0-7849-4f2a-ae84-0b53e15879f3.png)

2021-11-16 15:34 UTC, KrickRay commented
Почему, например, не это https://www.npmjs.com/package/ngx-bootstrap-icons ?

2021-11-22 12:03 UTC, KrickRay requested changes

2021-11-22 12:03 UTC, KrickRay commented on src/app/sections/claim-section/claim-modification-containers/file-container/file-container.component.scss
>  }
дел

2021-11-22 12:03 UTC, KrickRay commented on src/components/navigation/navbar-item/navbar-item.module.ts
> +    imports: [CommonModule, FlexLayoutModule, MatIconModule, MatSlideToggleModule, NgxBootstrapIconsModule.pick(ICONS)],
может все же на все приложение все это, модульно будет трудно поддерживать

2021-11-22 12:07 UTC, KrickRay commented on src/components/navigation/navbar-item/navbar-item.module.ts
> +};
IconName, который используется в коде, можно сделать локальным, ограниченным этим набором

2021-11-22 12:08 UTC, KrickRay commented on src/app/sections/payment-section/utils/to-navbar-item-config.ts
> +        icon: 'pie-chart',
можно взять из enum'a

2021-11-26 12:36 UTC, KeinAsylum commented
Сделано https://github.com/rbkmoney/dashboard/pull/594

2021-11-26 12:36 UTC, closed without merging